---
  - name: building dev platform
    hosts: all
    sudo: yes

    vars_files:
      - vars/main.yml

    pre_tasks:
      - name: install webtatic repo
        yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present

      - name: Install git
        yum: name=git state=latest

    roles:
      - geerlingguy.nginx
      - geerlingguy.php

    post_tasks:
      - name: Install PHP dependencies with composer
        shell: cd /sites && php composer.phar install
